- hosts: new
  user: root
  vars:
     zabbix_serverip: ****
     zabbix_activeip: ****
     agent_hostname: '{{ ansible_hostname }}'
     agent_ip: '{{ ansible_eth1.ipv4.address }}'
  roles:
    - zabbix_agent
  gather_facts: no
# 参数:gather_facts, 关闭fact数据获取, 即setup相关数据, 提高push效率

# yum
- name: yum update
  yum: name=* state=latest

- name: yum Development Tools
  yum:
    name: "@Development tools"
    state: present

- name: yum packages
  yum:
    name: [ 'libevent-devel', 'zlib-devel', 'openssl-devel', 'python-devel' ]

# copy
- name: copy Python-3.8.0.tgz
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - autoconf-2.69.tar.gz
    - bison-2.5.1.tar.gz
    - boost_1_56_0.tar.gz
    - thrift-0.13.0.tar.gz
    - automake-1.14.tar.gz

# shell
- name: install autoconf-2.69
  shell: |
      cd /tmp
      tar xvf autoconf-2.69.tar.gz
      cd autoconf-2.69
      ./configure --prefix=/usr
      make
      make install

# blockinfile
- name: insert /usr/local/python3/lib/python3.8/site-packages/deps.pth
  blockinfile:
      path: /usr/local/python3/lib/python3.8/site-packages/deps.pth
      block: |
          /opt/appuser/datacenter
          /opt/appuser/util
          /opt/appuser/thrift-gen
      create: yes
# 参数:create, 文件不存在需要创建, 使用create参数

# service
- name: enabled service
  service: name=daemontools enabled=yes

- name: start  service
  service: name=daemontools state=restarted

# file
- name: create directory it does not exist
  file:
    path: /opt/package
    state: directory
    mode: 1755

# 注册变量
- name: judge pkg is exists
  shell: ls /opt/nginx-1.17.4.tar.gz
  ignore_errors: yes
  register: pkg_result

- name: shell module return values
  debug:
    var: pkg_result.failed

- name: download pkg
  get_url:
    url: http://nginx.org/download/nginx-1.17.4.tar.gz
    dest: /opt
  when: pkg_result.failed == true

# j2
- name: up systemctl conf client
  template: src=nginx.service.j2 dest=/usr/lib/systemd/system/nginx.service
  
# lineinfile
- name: replace txt
  lineinfile:
    dest: /etc/sudoers
    regexp: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
# 参数insertbefore：在此之前添加
# 参数insertafter：在此之后添加
# 参数state: absent删除
