- name: yum update
  yum: name=* state=latest
- name: yum Development Tools
  yum: 
    name: "@Development tools"
    state: present
- name: yum packages
  yum:
    name: [ 'libevent-devel', 'zlib-devel', 'openssl-devel', 'python-devel' ]
- name: copy Python-3.8.0.tgz
  copy:
    src: "{{ item }}"
    dest: /tmp 
  with_items:
    - autoconf-2.69.tar.gz
    - bison-2.5.1.tar.gz
    - boost_1_56_0.tar.gz
    - thrift-0.13.0.tar.gz
    - automake-1.14.tar.gz
- name: install autoconf-2.69
  shell: |
      cd /tmp
      tar xvf autoconf-2.69.tar.gz
      cd autoconf-2.69
      ./configure --prefix=/usr
      make
      make install
- name: install automake-1.14
  shell: |
      cd /tmp
      tar xvf automake-1.14.tar.gz
      cd automake-1.14
      ./configure --prefix=/usr
      make
      make install
- name: install bison-2.5.1
  shell: |
      cd /tmp
      tar xvf bison-2.5.1.tar.gz
      cd bison-2.5.1
      ./configure --prefix=/usr
      make
      make install
- name: install boost_1_56_0
  shell: |
      cd /tmp
      tar xvf boost_1_56_0.tar.gz
      cd boost_1_56_0
      export CPLUS_INCLUDE_PATH=/usr/include/python2.7
      ./bootstrap.sh
      ./b2 install
- name: install thrift-0.13.0
  shell: |
      cd /tmp
      tar -xzvf thrift-0.13.0.tar.gz
      cd thrift-0.13.0
      ./configure --with-lua=no
      make
      make install
