#- name: yum pkg
#  yum:
#    name: ['zlib-devel', 'bzip2-devel', 'openssl-devel', 'ncurses-devel', 'sqlite-devel', 'readline-devel', 'tk-devel', 'gdbm-devel', 'db4-devel', 'libpcap-devel', 'xz-devel', 'libffi-devel', 'gcc']
#- name: copy Python-3.8.0.tgz
#  copy: src=Python-3.8.0.tgz dest=/tmp 
#- name: install Python3
#  shell: |
#      cd /tmp
#      tar -xzvf Python-3.8.0.tgz
#      cd Python-3.8.0
#      ./configure --prefix=/usr/local/python3
#      make
#      make install
#      ln -s /usr/local/python3/bin/python3 /usr/bin/python3
#- name: insert /etc/profile
#  blockinfile:
#      path: /etc/profile
#      block: |
#          export PATH=$PATH:$HOME/bin:/usr/local/python3/bin
#- name: insert /usr/local/python3/lib/python3.8/site-packages/deps.pth
#  blockinfile:
#      path: /usr/local/python3/lib/python3.8/site-packages/deps.pth
#      block: |
#          /opt/appuser/datacenter
#          /opt/appuser/util
#          /opt/appuser/thrift-gen
#      create: yes
#- name: copy requirements.txt
#  copy: src=requirements.txt dest=/root
- name: pip3 requirements
  shell: |
      source /etc/profile
      pip3 install --upgrade pip
      yum -y install mysql-devel
      pip3 install -r requirements.txt
