- name: install zabbix-agend
  shell: |
      rpm -ivh http://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
      yum install -y zabbix-agent
- name: up zabbix-agent file client
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
- name: enabled service zabbix-agent
  service: name=zabbix-agent enabled=yes
- name: start  service zabbix-agent
  service: name=zabbix-agent  state=started